export const motivationalQuotes = [
  "A real pirate never stops sailing, even when the sea gets rough.",
  "Your dream is your treasure—protect it like your life depends on it.",
  "A crewless ship drifts, but you are your own crew—steer yourself.",
  "Scars don’t define you; they remind you that you survived.",
  "Even the strongest waves bow to those who dare push forward.",
  "You don’t need permission to chase freedom.",
  "Weakness is only your starting point, not your identity.",
  "If the world tries to cage you, break the world’s rules.",
  "Legends are made from ordinary people who refused to quit.",
  "Every step on your journey counts—even the slow ones.",
  "The sea rewards the brave, not the perfect.",
  "Fear is just a storm; keep your sails up.",
  "Only you know how far your compass points.",
  "If the island you want doesn’t exist, create it.",
  "True strength appears when your dream is on the line.",
  "You can lose a battle and still win the war of destiny.",
  "Don’t search for the right moment—make it.",
  "Treasure isn’t gold; it’s the reason you keep moving.",
  "Storms don’t stop dreamers—they sharpen them.",
  "Your crew will find you when you start your journey.",
  "Nothing is impossible when your will is iron.",
  "Greatness starts with a stupid, impossible dream.",
  "If you fall seven times, rise like a new pirate each time.",
  "A map doesn’t make a navigator—courage does.",
  "The world’s judgments are just noise; sail anyway.",
  "A dream is only crazy until you achieve it.",
  "The ocean is vast because your potential is.",
  "Fight for the future your younger self believed in.",
  "Every emperor was a rookie once.",
  "Chase horizons, not comfort.",
  "Your will can shake worlds—if you dare use it.",
  "Victory is born from relentless faith.",
  "Even broken ships can cross oceans with enough hope.",
  "No dream is too big—only courage can be too small.",
  "Bring fire to your ambition; let it burn doubt away.",
  "Your destiny isn’t found—it’s built.",
  "There’s no shortcut to greatness, only direction.",
  "Every setback is another chapter in your legend.",
  "Your potential is deeper than any Grand Line sea.",
  "A king’s crown is forged in struggle.",
  "Be the storm that others fear.",
  "When the world tells you to stop, grin and go further.",
  "True pirates don’t chase fame—they chase purpose.",
  "A dream kept secret dies; one spoken aloud grows.",
  "Every ship needs an anchor—don’t let doubt be yours.",
  "Freedom belongs to those who fight for it.",
  "Rise even when the sea tries to drown you.",
  "The ones who laugh during battle are the strongest.",
  "Your dream should scare you; that’s how you know it’s real.",
  "Even a small spark can ignite a whole world.",
  "The sea tests you only because it knows you're worthy.",
  "Do not fear defeat; fear not trying.",
  "Your passion is your true devil fruit.",
  "A lonely journey still leads to treasure.",
  "Patience builds empires.",
  "The greatest treasure is a goal that wakes you up.",
  "Every hero starts as a nobody with a dream.",
  "The sea may swallow you, but your will decides if you drown.",
  "Dream so big the world calls you crazy.",
  "Your courage is louder than a thousand cannons.",
  "Don’t wait for the winds—be your own wind.",
  "Failure is the compass that redirects champions.",
  "A dream chased with heart becomes destiny.",
  "The world opens only for those who knock again and again.",
  "Be the captain of your story.",
  "The ocean bows to no one, but it follows the brave.",
  "Never underestimate the power of a determined idiot.",
  "Your heart is your Jolly Roger—raise it high.",
  "Courage is choosing to step forward when shaking.",
  "The path to greatness is unmarked—pave it.",
  "Every small victory brings you closer to the treasure.",
  "Believe in your dream until the whole world does too.",
  "Kings aren’t born—they crawl, walk, bleed, and rise.",
  "One day, your struggle will be your story of pride.",
  "Never fear chasing something others don’t understand.",
  "Even a sinking ship can reach shore with enough will.",
  "Your limits are illusions taught by doubt.",
  "Set your sails even if the sky is dark.",
  "A dream without risk is just a wish.",
  "Walk a path worth singing about.",
  "The world is huge—don’t shrink yourself.",
  "A brave heart can cut through any storm.",
  "If your dream scares you, chase harder.",
  "Make your will unbreakable.",
  "The treasure is great, but the journey makes you legendary.",
  "Every sunrise brings a chance to rewrite fate.",
  "Your spirit should roar louder than any sea king.",
  "Courage is choosing the dangerous path for a worthy dream.",
  "Let your ambition be bigger than your fears.",
  "The stronger your will, the smaller your obstacles.",
  "Walk alone until the right crew arrives.",
  "Dreams become real when failure becomes fuel.",
  "Face your doubts like a pirate facing a rival crew.",
  "Greatness requires sacrifice—don’t fear the price.",
  "The horizon is endless, so is your potential.",
  "Storms shape legends.",
  "The world fears those who can’t be broken.",
  "Keep going until even the sea respects you.",
  "True pirates don’t retreat—they rethink and strike.",
  "Let your conviction be sharp like a sword.",
  "One dream is enough to change the entire world.",
  "Even kings start as dreamers.",
  "Pain is temporary; pride is forever.",
  "A goal without struggle has no value.",
  "Your story isn’t over—it’s just beginning.",
  "Only you can decide the weight of your dream.",
  "Impossible just means untested.",
  "Raise your flag even when the wind is against you.",
  "Your scars sing your victory.",
  "A dream ignored becomes a regret.",
  "If you don’t give up, destiny has no choice.",
  "Break limits every day.",
  "Seek adventure in your own way.",
  "Nothing changes until you decide to.",
  "Your heart knows the way—follow it.",
  "Greatness begins with a single step.",
  "Your dream is the North Star—trust it.",
  "Don’t be the sailor who feared waves.",
  "Your courage will inspire others to rise.",
  "To create history, ignore opinions.",
  "A burning dream outshines any darkness.",
  "The world belongs to those who dare claim it.",
  "Failure teaches more than victory ever could.",
  "Protect your dream like a treasure chest.",
  "Your future self is counting on you.",
  "Face the unknown with a grin.",
  "Every champion was once uncertain.",
  "Be the storm, not the leaf.",
  "No treasure shines brighter than perseverance.",
  "Your will is your true weapon.",
  "Conquer your fears, then conquer the world.",
  "Even the deepest ocean can be crossed.",
  "You are stronger than yesterday.",
  "Whenever you doubt—remember why you started.",
  "Your effort will echo across time.",
  "The sea rewards the relentless.",
  "If you’re scared, move faster.",
  "Your dream needs action, not excuses.",
  "Chase greatness, not approval.",
  "Pressure creates legends.",
  "Dare to sail where others don’t.",
  "Let ambition be your ship.",
  "Your dream must be louder than your fear.",
  "A true pirate creates their own fate.",
  "Every loss pushes you closer to victory.",
  "Be unstoppable, even when tired.",
  "The world bows to unshakable willpower.",
  "Become someone your past self would admire.",
  "Dream fiercely, act boldly.",
  "You are your only rival.",
  "Trust your journey—even the messy parts.",
  "Rise like a pirate king every morning.",
  "Make your future self proud.",
  "Keep going—your moment will come.",
  "Not all treasures are found; some are earned.",
  "Your passion is your lighthouse.",
  "A thousand obstacles mean you’re on the right path.",
  "Be brave enough to be different.",
  "Let your journey be louder than their doubts.",
  "Your heart was made for big dreams.",
  "Prove your fears wrong.",
  "The risk makes the reward legendary.",
  "Walk forward even if the ground shakes.",
  "You’re closer than you think.",
  "Let determination be your eternal flame.",
  "Your story deserves greatness.",
  "No king wins without losing first.",
  "Wear your ambition like armor.",
  "Your dream doesn’t expire.",
  "Stand tall even alone.",
  "The sea is big—but your spirit is bigger.",
  "A battle you avoid is a battle you lose.",
  "You are the captain—act like it.",
  "Chase the dream that keeps you alive.",
  "The world changes when you do.",
  "Your dream is your destiny’s anchor.",
  "Believe in miracles—but work for them too.",
  "Courage is not the absence of fear—it's action despite it.",
  "Raise your flag even when torn.",
  "Your fire can light up nations.",
  "One brave decision can change everything.",
  "Be the legend your world needs.",
  "The ocean is wide enough for your ambition.",
  "The day you stop dreaming is the day you sink.",
  "Greatness grows through struggle.",
  "Be unstoppable like the tides.",
  "Your heart knows no limits.",
  "A warrior’s spirit never fades.",
  "You don’t need permission to shine.",
  "Grow stronger from every storm.",
  "You are destined for more—keep going.",
  "Even the sun rises after the darkest night.",
  "Great stories come from painful beginnings.",
  "Every legend was doubted first.",
  "Stand fearless in front of your dreams.",
  "What you build today becomes your future.",
  "Fight until the world recognizes your will.",
  "Courage turns dreams into reality.",
  "Choose the path that scares you the most—it holds treasure.",
  "Shout your dream so loud even fate hears it.",
  "Your heart is your helm.",
  "Be as wild as your dreams.",
  "Break every limit they try to give you.",
  "Your belief is your power.",
  "Treasure your ambition like gold.",
  "Keep pushing—the sea tests the worthy.",
  "Dream with hunger.",
  "Your strength grows in silence.",
  "Impossible is a challenge, not a fact.",
  "Be fierce enough to change your fate.",
  "Your future is waiting—go claim it.",
  "Every effort moves your ship forward.",
  "Let nothing dim your lighthouse.",
  "Fight like your dream depends on today.",
  "Every failure sharpens your blade.",
  "Your journey is holy—protect it.",
  "You were born for extraordinary things.",
  "Rise again until rising is easy.",
  "Never underestimate a burning heart.",
  "The sea respects only the relentless.",
  "Your dream should feel impossible—that’s how you know it’s worthy.",
  "Keep steering even when lost.",
  "Be proud of how far you’ve come.",
  "Let your dream roar louder than doubt.",
  "Your ambition is your destiny’s key.",
  "Fight for the life you imagine.",
  "Even your smallest step is progress.",
  "Your will is stronger than any storm.",
  "Believe like a pirate king.",
  "Make fear regret challenging you.",
  "Your journey shapes you more than the treasure.",
  "Let passion guide your sails.",
  "Nacho destiny—don’t wait for it.",
  "Become the one they said you couldn’t.",
  "You’re writing a legend—don’t stop now.",
  "Greatness requires bold choices.",
  "Your dream is worth every sacrifice.",
  "The brave rewrite reality.",
  "Every morning is a new chapter.",
  "Own your ambition—don’t hide it.",
  "Your future self will thank you for not giving up.",
  "True strength is refusing to quit.",
  "Be unstoppable, unshakable, undeniable.",
  "Your belief is your strongest weapon.",
  "Choose growth over comfort.",
  "Your fire can’t be extinguished.",
  "Dream louder than the world’s doubts.",
  "You were meant to stand out.",
  "Fight for your younger self.",
  "Let your heart be your guide.",
  "Greatness demands loyalty—to your dream.",
  "Act like your dream is already real.",
  "Success loves the relentless.",
  "Your mind is your map.",
  "If you can imagine it, you can chase it.",
  "Be a storm of ambition.",
  "The world changes when you refuse to give up.",
  "Your story deserves a legendary ending.",
  "Don’t shrink—expand.",
  "Your passion is your compass.",
  "Live boldly even if you fear failing.",
  "You were not born to be ordinary.",
  "Let perseverance be your legacy.",
  "Believe in your path—even if no one else does.",
  "Your dream owes you nothing—you owe it effort.",
  "Sail with courage, not certainty.",
  "Your destiny is waiting beyond the next wave.",
  "Be the fire that never fades.",
  "Your dream is stronger than your excuses.",
  "Greatness blooms from resilience.",
  "Let the world know you were here.",
  "Your will is your throne.",
  "Keep sailing—the treasure is ahead.",
  "You are capable of more than you think.",
  "Write a story worth screaming to the sky.",
  "Let ambition be your heartbeat.",
  "Bravery is choosing to continue.",
  "You’re one decision away from a new life.",
  "Lead your own revolution.",
  "Your dream should feel like oxygen.",
  "Failure builds the strongest warriors.",
  "Keep going—the world needs your fire.",
  "Your heart knows you’re destined for more.",
  "Fight harder than your fears.",
  "Dream like a pirate—wild and unstoppable.",
  "You are the storm breaker.",
  "Treasure your progress.",
  "One day, your struggle will inspire millions.",
  "Your potential is limitless.",
  "Be the captain fate respects.",
  "Go beyond what you think you can.",
  "Your dream deserves daily effort.",
  "Rise again, stronger each time.",
  "You are built for greatness.",
  "Let no one dim the fire inside you.",
  "Your destiny is crafted by your hands.",
  "Big dreams require big courage.",
  "Even small steps shake destiny.",
  "Never apologize for dreaming big.",
  "The sea bows to relentless hearts.",
  "You are the master of your future.",
  "Fight until your dream becomes your reality.",
  "Let your heart lead your ship.",
  "Be the reason your world changes.",
  "You are closer to greatness than you realize.",
  "Keep pushing, keep growing.",
  "Fear doesn’t stand a chance against will.",
  "You’re writing a legend—don’t stop.",
  "Every trial sharpens you.",
  "Dream with fire, act with steel.",
  "Your ambition should scare you a little.",
  "Live boldly—your destiny demands it.",
  "Let courage drown your doubt.",
  "You are unstoppable when focused.",
  "Chase purpose, not perfection.",
  "Your dream is worth every sleepless night.",
  "Fight until fate bends.",
  "No warrior rises without pain.",
  "The treasure you seek is waiting for your courage.",
  "Every day is another chance to rise.",
  "Believe like your dream is inevitable.",
  "You are stronger than the storms you’ve survived.",
  "Your story is far from over.",
  "Walk the path only you can see.",
  "Your dream deserves a fighter.",
  "Fight with conviction, not doubt.",
  "Treasure your ambition—it's your lifeline.",
  "The sea obeys the bold.",
  "No legend is made in comfort.",
  "Your dream is a promise—honor it.",
  "Let your spirit roar louder than fear.",
  "Every sunrise is a second chance.",
  "You’re destined for something extraordinary.",
  "Go further than anyone expects.",
  "Your courage will build your kingdom.",
  "Be the reason impossible becomes possible.",
  "Your dream is bigger than your obstacles.",
  "Never stop evolving.",
  "The world will remember your will.",
  "Your ambition is your anchor and your sail.",
  "Keep moving forward—always.",
  "You are your only limit.",
  "Your destiny waits on the other side of fear.",
  "A burning heart never loses.",
  "Write your story with bravery.",
  "You are a storm of potential.",
  "The brave create their own luck.",
  "Your future is shaped by your today.",
  "Don’t wait—begin.",
  "Your dream must be chased fiercely.",
  "Let nothing stop your momentum.",
  "You were made for high seas and high dreams.",
  "Rise until rising becomes easy.",
  "Your heart is stronger than your doubts.",
  "Dream boldly—act bravely.",
  "The world needs your ambition.",
  "Push beyond your limits.",
  "Your story is your power.",
  "Even kings start from nothing.",
  "Believe you can—and you will.",
  "Your fire is eternal.",
  "Let your dream be your North Star.",
  "Great things take time—move anyway.",
  "You are capable of impossible things.",
  "Raise your flag—your era is coming.",
  "The more that you read, the more things you will know.",
  "Strength rises when you stand again after falling.",
  "Your courage today becomes your legend tomorrow.",
  "Let determination ride every wave with you.",
  "Your dream deserves a fearless captain.",
  "Every tough night leads to a brighter dawn.",
  "Push forward even when the sea roars against you.",
  "Your willpower can tame even the stormiest tides.",
  "Greatness grows in those who endure the longest.",
  "A pirate's heart never surrenders to fear.",
  "The sea only tests those who are destined for more.",
  "Your dream is worth every sleepless night.",
  "Rise again—each fall sharpens your spirit.",
  "Let your purpose shine through the darkest storms.",
  "Your ambition can break chains the world puts on you.",
  "Every wave brings another chance to grow.",
  "Stand firm—your destiny needs your strength.",
  "Let your dream pull you forward like the strongest tide.",
  "Courage becomes real when fear stands in front of you.",
  "Your spirit is stronger than any whirlpool of doubt.",
  "The future belongs to pirates who never stop trying.",
  "Let your efforts echo across your entire journey.",
  "Your dream becomes unstoppable when you commit fully.",
  "Every storm you face builds your legend.",
  "Even the quietest determination can move mountains.",
  "Your destiny is shaped by the waves you conquer.",
  "Let your heart guide your sails.",
  "Each new day brings a new treasure to find.",
  "Your strength comes from how much you’ve survived.",
  "Be the pirate who keeps going when all seems lost.",
  "Your courage can turn small steps into giant leaps.",
  "Let the world hear your ambition through your actions.",
  "Every dream requires the courage to begin.",
  "Your persistence is your true Devil Fruit.",
  "Great pirates rise from ordinary beginnings.",
  "Your effort today decides your treasure tomorrow.",
  "Let the fire inside you burn brighter than fear.",
  "The sea rewards only the brave-hearted.",
  "Your dream doesn’t grow unless you chase it.",
  "Courage transforms impossible into possible.",
  "Your journey becomes legendary through struggle.",
  "Believe in your sails even when there’s no wind.",
  "Let your fear become your fuel.",
  "Your determination is stronger than the fiercest storm.",
  "Every step you take builds your pirate legacy.",
  "Greatness demands the courage to continue.",
  "Your heart knows the way—follow it boldly.",
  "Let nothing dull the shine of your ambition.",
  "Your dream needs your faith, not hesitation.",
  "The sea clears paths for those who persist.",
  "Every wave you cross brings new growth.",
  "Your story becomes powerful when you refuse to quit.",
  "Let your will be unshakable like the Pirate King's.",
  "Every sunrise carries a message: keep going.",
  "Your courage can calm even the wildest seas.",
  "Stay strong—storms make you unstoppable.",
  "Your inner fire can survive any ocean.",
  "Only determined pirates reach the rarest treasures.",
  "Let every struggle make you sharper.",
  "Your dream is the map—your effort is the journey.",
  "Never let fear hold your anchor.",
  "Your resolve can cut through any obstacle.",
  "Let each failure sculpt you into greatness.",
  "You shine brightest when you move forward despite fear.",
  "Your story hasn’t even reached its best chapter.",
  "The sea favors pirates with unbreakable spirits.",
  "Let your ambition echo across oceans.",
  "Your future is built by the choices you make today.",
  "With courage, every wave becomes smaller.",
  "Your strength grows in silence and explodes in success.",
  "Let your dream be louder than any discouragement.",
  "Only persistent hearts unlock legendary destinies.",
  "Your path may be rough, but so is your spirit.",
  "Let hope guide you through unseen waters.",
  "Your dream deserves the version of you that never quits.",
  "Even in darkness, your will can shine like a lighthouse.",
  "Let every challenge sharpen your sails.",
  "Your courage can change the direction of your fate.",
  "One brave decision can rewrite your entire story.",
  "Let your dream sail further than fear ever could.",
  "Your strength lies in refusing to give up.",
  "Greatness begins the moment you decide to continue.",
  "Your heart carries the spirit of a true pirate.",
  "Let your belief be the mast that never breaks.",
  "Your future treasure depends on today’s effort.",
  "Every storm strengthens your soul.",
  "Let your dream shine even when skies turn gray.",
  "Your fight today creates tomorrow's reward.",
  "Stay relentless—the sea respects persistence.",
  "Your ambition can turn storms into stepping stones.",
  "Let nothing stop your ship from reaching its island.",
  "Every island you dream of exists on the other side of courage.",
  "Hold your flag high even when you're the only one waving it.",
  "Your strength grows every time you choose not to quit.",
  "The ocean bows to the pirate who never stops rowing.",
  "Your ambition should roar louder than thunder.",
  "Every new day is another island waiting to be conquered.",
  "Trust your compass even when the world questions your path.",
  "You don't need calm seas—you need an unshakable spirit.",
  "The journey is tough, but so are you.",
  "Every scar is proof that you kept moving forward.",
  "A captain doesn't wait for chances—he creates them.",
  "The sea respects relentless hearts.",
  "Your dream is your treasure—guard it fiercely.",
  "Effort is the strongest weapon any pirate can carry.",
  "Every wave is a step closer to greatness.",
  "Let your actions speak louder than your fears.",
  "A true pirate grows stronger with every failure.",
  "Your courage defines the size of your ship.",
  "Those who endure storms taste sweeter victories.",
  "Your willpower can outshine the darkest clouds.",
  "Greatness isn’t found on the shore—sail further.",
  "Your dream deserves every bit of struggle.",
  "Keep fighting; treasure lies beyond breaking points.",
  "Even lone pirates can shake the world.",
  "Your fire must keep burning even in heavy rain.",
  "Believe in your future self like a captain believes in his crew.",
  "Strong seas build stronger pirates.",
  "The horizon is only the beginning of your legend.",
  "Your ship moves as far as your courage allows.",
  "Fear loses power when you face it head-on.",
  "Only the brave find the rarest treasures.",
  "Your journey is your greatest adventure.",
  "No storm can drown a determined soul.",
  "Progress is slow, but quitting is instant defeat.",
  "Every challenge you face becomes part of your bounty.",
  "The world fears pirates with unbreakable dreams.",
  "Your resolve should shine brighter than your doubts.",
  "Stand tall even when the waves try to swallow you.",
  "Small steps create mighty journeys.",
  "Every storm shapes you into someone unstoppable.",
  "A pirate with purpose is stronger than a thousand without.",
  "Your dream is worth every sacrifice.",
  "You rise higher each time you refuse to fall.",
  "Let determination be the anchor of your soul.",
  "Storms test your strength, not your destiny.",
  "Every wave carries a lesson—learn and move on.",
  "A true pirate never lets fear steer the ship.",
  "Greatness belongs to those who fight for it.",
  "Your dream grows with every step forward.",
  "Be the pirate who keeps going when others surrender.",
  "The sea is tough, but so are you.",
  "Every sunrise gives you another chance to rise stronger.",
  "Let hope be the wind pushing your sails.",
  "Your courage writes your legend.",
  "Tough seas shape legendary pirates.",
  "Let ambition guide your sail, not fear.",
  "Your dream deserves consistency, not excuses.",
  "A pirate chasing greatness never sails backward.",
  "Every failure is a new route, not a dead end.",
  "Your next step could unlock hidden treasure.",
  "You are stronger than the waves you fear.",
  "Greatness blooms when you choose effort over comfort.",
  "Your heart knows the route—trust it.",
  "Your story becomes legendary when you don’t quit.",
  "The sea rewards those who dare to explore.",
  "Push through the winds that try to hold you back.",
  "Your destiny begins when fear ends.",
  "Every day you sail is a day closer to your dream.",
  "Your inner strength is the real treasure.",
  "Let nothing dim the fire burning inside you.",
  "Your courage is worth more than any gold.",
  "Every storm you survive makes you harder to sink.",
  "Be your own lighthouse in dark nights.",
  "Your potential is deeper than the sea itself.",
  "Hard days create fearless pirates.",
  "A pirate’s heart never bows to doubt.",
  "Keep sailing—your treasure awaits.",
  "Your dream needs your fight, not your fear.",
  "Only the determined reach the greatest islands.",
  "Let passion fuel your sails every day.",
  "The rougher the sea, the greater the reward.",
  "Your effort today builds your victory tomorrow.",
  "Even a small spark can ignite a pirate’s destiny.",
  "Every challenge strengthens your spirit.",
  "Believe in your sails even in silent winds.",
  "Your will can conquer oceans.",
  "Hardships carve the strongest pirates.",
  "Keep walking your map—your treasure is near.",
  "Let bravery replace hesitation.",
  "Every fall prepares you for the next rise.",
  "Trust the journey—even the painful parts.",
  "Your courage can silence roaring waves.",
  "Your anchor should be hope, not fear.",
  "Even the strongest pirates were once scared to set sail.",
  "Let your spirit be louder than the raging storm.",
  "Every wave you cross builds your legend.",
  "Greatness begins the moment you refuse to quit.",
  "A pirate’s heart is unshakable when fueled by purpose.",
  "Your dream is your eternal compass—trust it.",
  "True strength comes from standing back up.",
  "The ocean rewards those who dare first.",
  "Let your ambition shine brighter than the sun.",
  "Every island you reach is proof you didn’t give up.",
  "The sea tests only those capable of greatness.",
  "Courage is forged in the heat of struggle.",
  "Your dream is the ship; your will is the sails.",
  "Only those who risk everything become legends.",
  "Your journey matters more than your destination.",
  "Every sunrise is another chance to sail forward.",
  "Fear melts when you take the first step.",
  "A bold pirate never stops growing.",
  "Your destiny is built through relentless effort.",
  "Strong determination beats stronger enemies.",
  "Even the smallest spark can light a pirate’s soul.",
  "Every challenge sharpens your blade.",
  "Your ship sails faster when doubt jumps overboard.",
  "Treasure the process; mastery comes with waves.",
  "Every wound is proof you fought bravely.",
  "The next island is always worth the effort.",
  "A true captain guides himself through darkness.",
  "The harder the storm, the greater the triumph.",
  "Your ambition is the lighthouse in harsh nights.",
  "Dreams grow when you feed them with action.",
  "Fight for your destiny like a pirate fights for treasure.",
  "The sea bows to those who never break.",
  "Push forward even when the world pushes back.",
  "Your courage is your most valuable bounty.",
  "Only those who climb the mast see the horizon.",
  "Every trial strengthens your sails.",
  "Your fears crumble when faced with determination.",
  "Strength grows from choosing the difficult route.",
  "Real pirates rise after a hundred falls.",
  "Your heart holds power no sea can drown.",
  "Not all treasure is gold—some is growth.",
  "Believe in the pirate you’re becoming.",
  "The ocean belongs to those who dare to explore.",
  "Your dream thrives when excuses sink.",
  "A powerful will cuts through any storm.",
  "Every failure sharpens your future victories.",
  "Never fear the unknown—fear standing still.",
  "The sea teaches discipline, courage, and hope.",
  "Let ambition be the wind beneath your sail.",
  "Your next step might lead to treasure—take it.",
  "Legends are made by those who never retreat.",
  "Even quiet pirates have loud dreams.",
  "You grow by choosing the harder wave.",
  "A captain trusts his decisions, even alone.",
  "Every dark cloud carries the promise of dawn.",
  "Your progress is your personal treasure map.",
  "The world cannot stop a determined pirate.",
  "Your journey will inspire future sailors.",
  "Let nothing dim the fire in your spirit.",
  "Storms create the strongest pirate kings.",
  "The first wave is the hardest—sail anyway.",
  "Your power lies in your persistence.",
  "Conquer your thoughts and you conquer the sea.",
  "Big dreams require a fearless heart.",
  "Believe in your strength even when others don’t.",
  "Your path is yours—don’t compare ships.",
  "Every tide brings new lessons.",
  "Work quietly; let your success roar like a sea king.",
  "Your resilience is your greatest weapon.",
  "Even in silence, dreams grow louder.",
  "Only effort can unlock hidden treasure.",
  "The sea respects only unwavering will.",
  "Adventure begins where comfort ends.",
  "Your potential is deeper than any ocean.",
  "Grow stronger than yesterday’s waves.",
  "Your heart is a pirate flag—raise it proudly.",
  "Those who endure the storm earn the calm.",
  "Let your dedication steer your destiny.",
  "Every setback is a chance to rebuild stronger.",
  "Your will can outshine the darkest night.",
  "Every wave you survive proves your worth.",
  "Great pirates are forged from hardships.",
  "Your dream is worth every fight.",
  "Take risks; safe seas create boring stories.",
  "Your determination can split open mountains.",
  "Choose effort over excuses—always.",
  "The sea favors those who never stop trying.",
  "Courage is found in the next step you take.",
  "Your story is just beginning—keep sailing.",
  "Let passion be your eternal flame.",
  "Impossible is just another enemy to defeat.",
  "Courageous hearts create unforgettable voyages.",
  "Your dream deserves the strongest version of you.",
  "The ocean doesn’t choose captains; captains rise by choice.",
  "A real pirate faces storms, not calm waters.",
  "Your dream won’t sail itself—grab the helm.",
  "Even a small ship can conquer a giant wave with courage.",
  "A crewless heart drifts; find your purpose and sail.",
  "Scars prove you kept moving when others stopped.",
  "No treasure shines brighter than self-belief.",
  "Every island of success needs a sea of struggle.",
  "Fear is the sea king you must tame.",
  "You become stronger every time you refuse to sink.",
  "A true captain stands tall even when the wind betrays him.",
  "Your will is your log pose—follow it.",
  "The Grand Line rewards only the brave.",
  "Every setback is a new map in disguise.",
  "Treasure your journey more than the gold.",
  "No Devil Fruit can replace hard work.",
  "Even Yonko were once rookies.",
  "Strong waves create stronger pirates.",
  "Your ship moves only when you do.",
  "The sea bows to no one—earn your place.",
  "Keep rowing even when nobody believes in your island.",
  "The world calls it impossible until a pirate proves them wrong.",
  "One step each day keeps your dream alive.",
  "A pirate’s promise is made with action, not words.",
  "When the storm hits, anchor your resolve.",
  "Your crew begins with you believing in yourself.",
  "The treasure you seek is hiding behind fear.",
  "Nothing changes unless you set sail.",
  "A captain never abandons his dream.",
  "The hardest journeys create legendary stories.",
  "Small victories lead to grand adventures.",
  "The sea teaches what comfort never will.",
  "Don’t wait for perfect winds—create your own.",
  "Your inner compass knows the way.",
  "When the world blocks your route, chart a new map.",
  "Never fear deep waters; fear shallow ambitions.",
  "The ocean rewards those who dive the deepest.",
  "Even shipwrecks can become turning points.",
  "Your spirit is stronger than any storm.",
  "A pirate grows by challenging stronger seas.",
  "The first step onto your ship is the bravest one.",
  "Stand tall; even giants started tiny.",
  "Without risk, no treasure is worth finding.",
  "A calm sea never made a fearless pirate.",
  "The tides change—keep adapting.",
  "Every dawn brings a new island to discover.",
  "Your courage is your greatest weapon.",
  "Never let doubt steer your ship.",
  "Chase dreams, not comfort.",
  "Even a broken mast can sail with determination.",
  "Your heart is your real bounty.",
  "The world’s judgment is just background noise.",
  "Every pirate trip begins with a single wave.",
  "A defeated pirate becomes a legendary one when he stands again.",
  "Patience builds stronger ships.",
  "Your dream is your eternal flag—never lower it.",
  "The sea respects only persistence.",
  "Every failure washes you closer to treasure.",
  "The dangerous seas show who you truly are.",
  "Find your purpose, and the winds will follow.",
  "Sail beyond the limits set by others.",
  "Your destiny starts where fear ends.",
  "Treasure your progress, even if small.",
  "Trust your journey, even when the skies darken.",
  "Your willpower can split mountains.",
  "Learn from storms, don’t fear them.",
  "Your ship sails faster when you drop your doubts.",
  "Chasing dreams is the greatest adventure.",
  "Don’t wait for rescue—be your own lifeboat.",
  "Even shadows exist because you’re shining.",
  "Your strength grows with every wave you conquer.",
  "The sea gives its best to those who endure its worst.",
  "You are your own captain—never forget that.",
  "Every trial is a new island on your map.",
  "Stand up again; legends don’t stay down.",
  "Great pirates rise from ordinary docks.",
  "Your heart knows the route to greatness.",
  "A dream worth having is a dream worth fighting for.",
  "The tides won’t favor you—push through anyway.",
  "Hard days build kingly spirits.",
  "A pirate’s courage glows brightest in darkness.",
  "Set your gaze on the horizon, not on doubts.",
  "Ambition is the wind inside your sails.",
  "Wake up with purpose like a pirate chasing treasure.",
  "Let your dream roar louder than any sea king.",
  "Every storm is temporary; your will is not.",
  "The greatest treasure is the person you become.",
  "Move forward even if waves pull you back.",
  "Your journey shapes your legend.",
  "Believe in your ship even when others laugh.",
  "The ocean is wide, but your resolve must be wider.",
  "A captain never fears rough waters.",
  "Sail with pride; every wave is a lesson.",
  "Uncertainty is the start of every adventure.",

];


export const getRandomQuote = (exclude: number[] = []): { quote: string; index: number } => {
  const available = motivationalQuotes
    .map((q, i) => ({ quote: q, index: i }))
    .filter(item => !exclude.includes(item.index));

  if (available.length === 0) {
    // Reset if all seen
    const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
    return { quote: motivationalQuotes[randomIndex], index: randomIndex };
  }

  const randomItem = available[Math.floor(Math.random() * available.length)];
  return randomItem;
};
