export const motivationalQuotes = [
  "A real pirate never stops sailing, even when the sea gets rough.",
  "Your dream is your treasure—protect it like your life depends on it.",
  "A crewless ship drifts, but you are your own crew—steer yourself.",
  "Scars don’t define you; they remind you that you survived.",
  "Even the strongest waves bow to those who dare push forward.",
  "You don’t need permission to chase freedom.",
  "Weakness is only your starting point, not your identity.",
  "If the world tries to cage you, break the world’s rules.",
  "Legends are made from ordinary people who refused to quit.",
  "Every step on your journey counts—even the slow ones.",
  "The sea rewards the brave, not the perfect.",
  "Fear is just a storm; keep your sails up.",
  "Only you know how far your compass points.",
  "If the island you want doesn’t exist, create it.",
  "True strength appears when your dream is on the line.",
  "You can lose a battle and still win the war of destiny.",
  "Don’t search for the right moment—make it.",
  "Treasure isn’t gold; it’s the reason you keep moving.",
  "Storms don’t stop dreamers—they sharpen them.",
  "Your crew will find you when you start your journey.",
  "Nothing is impossible when your will is iron.",
  "Greatness starts with a stupid, impossible dream.",
  "If you fall seven times, rise like a new pirate each time.",
  "A map doesn’t make a navigator—courage does.",
  "The world’s judgments are just noise; sail anyway.",
  "A dream is only crazy until you achieve it.",
  "The ocean is vast because your potential is.",
  "Fight for the future your younger self believed in.",
  "Every emperor was a rookie once.",
  "Chase horizons, not comfort.",
  "Your will can shake worlds—if you dare use it.",
  "Victory is born from relentless faith.",
  "Even broken ships can cross oceans with enough hope.",
  "No dream is too big—only courage can be too small.",
  "Bring fire to your ambition; let it burn doubt away.",
  "Your destiny isn’t found—it’s built.",
  "There’s no shortcut to greatness, only direction.",
  "Every setback is another chapter in your legend.",
  "Your potential is deeper than any Grand Line sea.",
  "A king’s crown is forged in struggle.",
  "Be the storm that others fear.",
  "When the world tells you to stop, grin and go further.",
  "True pirates don’t chase fame—they chase purpose.",
  "A dream kept secret dies; one spoken aloud grows.",
  "Every ship needs an anchor—don’t let doubt be yours.",
  "Freedom belongs to those who fight for it.",
  "Rise even when the sea tries to drown you.",
  "The ones who laugh during battle are the strongest.",
  "Your dream should scare you; that’s how you know it’s real.",
  "Even a small spark can ignite a whole world.",
  "The sea tests you only because it knows you're worthy.",
  "Do not fear defeat; fear not trying.",
  "Your passion is your true devil fruit.",
  "A lonely journey still leads to treasure.",
  "Patience builds empires.",
  "The greatest treasure is a goal that wakes you up.",
  "Every hero starts as a nobody with a dream.",
  "The sea may swallow you, but your will decides if you drown.",
  "Dream so big the world calls you crazy.",
  "Your courage is louder than a thousand cannons.",
  "Don’t wait for the winds—be your own wind.",
  "Failure is the compass that redirects champions.",
  "A dream chased with heart becomes destiny.",
  "The world opens only for those who knock again and again.",
  "Be the captain of your story.",
  "The ocean bows to no one, but it follows the brave.",
  "Never underestimate the power of a determined idiot.",
  "Your heart is your Jolly Roger—raise it high.",
  "Courage is choosing to step forward when shaking.",
  "The path to greatness is unmarked—pave it.",
  "Every small victory brings you closer to the treasure.",
  "Believe in your dream until the whole world does too.",
  "Kings aren’t born—they crawl, walk, bleed, and rise.",
  "One day, your struggle will be your story of pride.",
  "Never fear chasing something others don’t understand.",
  "Even a sinking ship can reach shore with enough will.",
  "Your limits are illusions taught by doubt.",
  "Set your sails even if the sky is dark.",
  "A dream without risk is just a wish.",
  "Walk a path worth singing about.",
  "The world is huge—don’t shrink yourself.",
  "A brave heart can cut through any storm.",
  "If your dream scares you, chase harder.",
  "Make your will unbreakable.",
  "The treasure is great, but the journey makes you legendary.",
  "Every sunrise brings a chance to rewrite fate.",
  "Your spirit should roar louder than any sea king.",
  "Courage is choosing the dangerous path for a worthy dream.",
  "Let your ambition be bigger than your fears.",
  "The stronger your will, the smaller your obstacles.",
  "Walk alone until the right crew arrives.",
  "Dreams become real when failure becomes fuel.",
  "Face your doubts like a pirate facing a rival crew.",
  "Greatness requires sacrifice—don’t fear the price.",
  "The horizon is endless, so is your potential.",
  "Storms shape legends.",
  "The world fears those who can’t be broken.",
  "Keep going until even the sea respects you.",
  "True pirates don’t retreat—they rethink and strike.",
  "Let your conviction be sharp like a sword.",
  "One dream is enough to change the entire world.",
  "Even kings start as dreamers.",
  "Pain is temporary; pride is forever.",
  "A goal without struggle has no value.",
  "Your story isn’t over—it’s just beginning.",
  "Only you can decide the weight of your dream.",
  "Impossible just means untested.",
  "Raise your flag even when the wind is against you.",
  "Your scars sing your victory.",
  "A dream ignored becomes a regret.",
  "If you don’t give up, destiny has no choice.",
  "Break limits every day.",
  "Seek adventure in your own way.",
  "Nothing changes until you decide to.",
  "Your heart knows the way—follow it.",
  "Greatness begins with a single step.",
  "Your dream is the North Star—trust it.",
  "Don’t be the sailor who feared waves.",
  "Your courage will inspire others to rise.",
  "To create history, ignore opinions.",
  "A burning dream outshines any darkness.",
  "The world belongs to those who dare claim it.",
  "Failure teaches more than victory ever could.",
  "Protect your dream like a treasure chest.",
  "Your future self is counting on you.",
  "Face the unknown with a grin.",
  "Every champion was once uncertain.",
  "Be the storm, not the leaf.",
  "No treasure shines brighter than perseverance.",
  "Your will is your true weapon.",
  "Conquer your fears, then conquer the world.",
  "Even the deepest ocean can be crossed.",
  "You are stronger than yesterday.",
  "Whenever you doubt—remember why you started.",
  "Your effort will echo across time.",
  "The sea rewards the relentless.",
  "If you’re scared, move faster.",
  "Your dream needs action, not excuses.",
  "Chase greatness, not approval.",
  "Pressure creates legends.",
  "Dare to sail where others don’t.",
  "Let ambition be your ship.",
  "Your dream must be louder than your fear.",
  "A true pirate creates their own fate.",
  "Every loss pushes you closer to victory.",
  "Be unstoppable, even when tired.",
  "The world bows to unshakable willpower.",
  "Become someone your past self would admire.",
  "Dream fiercely, act boldly.",
  "You are your only rival.",
  "Trust your journey—even the messy parts.",
  "Rise like a pirate king every morning.",
  "Make your future self proud.",
  "Keep going—your moment will come.",
  "Not all treasures are found; some are earned.",
  "Your passion is your lighthouse.",
  "A thousand obstacles mean you’re on the right path.",
  "Be brave enough to be different.",
  "Let your journey be louder than their doubts.",
  "Your heart was made for big dreams.",
  "Prove your fears wrong.",
  "The risk makes the reward legendary.",
  "Walk forward even if the ground shakes.",
  "You’re closer than you think.",
  "Let determination be your eternal flame.",
  "Your story deserves greatness.",
  "No king wins without losing first.",
  "Wear your ambition like armor.",
  "Your dream doesn’t expire.",
  "Stand tall even alone.",
  "The sea is big—but your spirit is bigger.",
  "A battle you avoid is a battle you lose.",
  "You are the captain—act like it.",
  "Chase the dream that keeps you alive.",
  "The world changes when you do.",
  "Your dream is your destiny’s anchor.",
  "Believe in miracles—but work for them too.",
  "Courage is not the absence of fear—it's action despite it.",
  "Raise your flag even when torn.",
  "Your fire can light up nations.",
  "One brave decision can change everything.",
  "Be the legend your world needs.",
  "The ocean is wide enough for your ambition.",
  "The day you stop dreaming is the day you sink.",
  "Greatness grows through struggle.",
  "Be unstoppable like the tides.",
  "Your heart knows no limits.",
  "A warrior’s spirit never fades.",
  "You don’t need permission to shine.",
  "Grow stronger from every storm.",
  "You are destined for more—keep going.",
  "Even the sun rises after the darkest night.",
  "Great stories come from painful beginnings.",
  "Every legend was doubted first.",
  "Stand fearless in front of your dreams.",
  "What you build today becomes your future.",
  "Fight until the world recognizes your will.",
  "Courage turns dreams into reality.",
  "Choose the path that scares you the most—it holds treasure.",
  "Shout your dream so loud even fate hears it.",
  "Your heart is your helm.",
  "Be as wild as your dreams.",
  "Break every limit they try to give you.",
  "Your belief is your power.",
  "Treasure your ambition like gold.",
  "Keep pushing—the sea tests the worthy.",
  "Dream with hunger.",
  "Your strength grows in silence.",
  "Impossible is a challenge, not a fact.",
  "Be fierce enough to change your fate.",
  "Your future is waiting—go claim it.",
  "Every effort moves your ship forward.",
  "Let nothing dim your lighthouse.",
  "Fight like your dream depends on today.",
  "Every failure sharpens your blade.",
  "Your journey is holy—protect it.",
  "You were born for extraordinary things.",
  "Rise again until rising is easy.",
  "Never underestimate a burning heart.",
  "The sea respects only the relentless.",
  "Your dream should feel impossible—that’s how you know it’s worthy.",
  "Keep steering even when lost.",
  "Be proud of how far you’ve come.",
  "Let your dream roar louder than doubt.",
  "Your ambition is your destiny’s key.",
  "Fight for the life you imagine.",
  "Even your smallest step is progress.",
  "Your will is stronger than any storm.",
  "Believe like a pirate king.",
  "Make fear regret challenging you.",
  "Your journey shapes you more than the treasure.",
  "Let passion guide your sails.",
  "Nacho destiny—don’t wait for it.",
  "Become the one they said you couldn’t.",
  "You’re writing a legend—don’t stop now.",
  "Greatness requires bold choices.",
  "Your dream is worth every sacrifice.",
  "The brave rewrite reality.",
  "Every morning is a new chapter.",
  "Own your ambition—don’t hide it.",
  "Your future self will thank you for not giving up.",
  "True strength is refusing to quit.",
  "Be unstoppable, unshakable, undeniable.",
  "Your belief is your strongest weapon.",
  "Choose growth over comfort.",
  "Your fire can’t be extinguished.",
  "Dream louder than the world’s doubts.",
  "You were meant to stand out.",
  "Fight for your younger self.",
  "Let your heart be your guide.",
  "Greatness demands loyalty—to your dream.",
  "Act like your dream is already real.",
  "Success loves the relentless.",
  "Your mind is your map.",
  "If you can imagine it, you can chase it.",
  "Be a storm of ambition.",
  "The world changes when you refuse to give up.",
  "Your story deserves a legendary ending.",
  "Don’t shrink—expand.",
  "Your passion is your compass.",
  "Live boldly even if you fear failing.",
  "You were not born to be ordinary.",
  "Let perseverance be your legacy.",
  "Believe in your path—even if no one else does.",
  "Your dream owes you nothing—you owe it effort.",
  "Sail with courage, not certainty.",
  "Your destiny is waiting beyond the next wave.",
  "Be the fire that never fades.",
  "Your dream is stronger than your excuses.",
  "Greatness blooms from resilience.",
  "Let the world know you were here.",
  "Your will is your throne.",
  "Keep sailing—the treasure is ahead.",
  "You are capable of more than you think.",
  "Write a story worth screaming to the sky.",
  "Let ambition be your heartbeat.",
  "Bravery is choosing to continue.",
  "You’re one decision away from a new life.",
  "Lead your own revolution.",
  "Your dream should feel like oxygen.",
  "Failure builds the strongest warriors.",
  "Keep going—the world needs your fire.",
  "Your heart knows you’re destined for more.",
  "Fight harder than your fears.",
  "Dream like a pirate—wild and unstoppable.",
  "You are the storm breaker.",
  "Treasure your progress.",
  "One day, your struggle will inspire millions.",
  "Your potential is limitless.",
  "Be the captain fate respects.",
  "Go beyond what you think you can.",
  "Your dream deserves daily effort.",
  "Rise again, stronger each time.",
  "You are built for greatness.",
  "Let no one dim the fire inside you.",
  "Your destiny is crafted by your hands.",
  "Big dreams require big courage.",
  "Even small steps shake destiny.",
  "Never apologize for dreaming big.",
  "The sea bows to relentless hearts.",
  "You are the master of your future.",
  "Fight until your dream becomes your reality.",
  "Let your heart lead your ship.",
  "Be the reason your world changes.",
  "You are closer to greatness than you realize.",
  "Keep pushing, keep growing.",
  "Fear doesn’t stand a chance against will.",
  "You’re writing a legend—don’t stop.",
  "Every trial sharpens you.",
  "Dream with fire, act with steel.",
  "Your ambition should scare you a little.",
  "Live boldly—your destiny demands it.",
  "Let courage drown your doubt.",
  "You are unstoppable when focused.",
  "Chase purpose, not perfection.",
  "Your dream is worth every sleepless night.",
  "Fight until fate bends.",
  "No warrior rises without pain.",
  "The treasure you seek is waiting for your courage.",
  "Every day is another chance to rise.",
  "Believe like your dream is inevitable.",
  "You are stronger than the storms you’ve survived.",
  "Your story is far from over.",
  "Walk the path only you can see.",
  "Your dream deserves a fighter.",
  "Fight with conviction, not doubt.",
  "Treasure your ambition—it's your lifeline.",
  "The sea obeys the bold.",
  "No legend is made in comfort.",
  "Your dream is a promise—honor it.",
  "Let your spirit roar louder than fear.",
  "Every sunrise is a second chance.",
  "You’re destined for something extraordinary.",
  "Go further than anyone expects.",
  "Your courage will build your kingdom.",
  "Be the reason impossible becomes possible.",
  "Your dream is bigger than your obstacles.",
  "Never stop evolving.",
  "The world will remember your will.",
  "Your ambition is your anchor and your sail.",
  "Keep moving forward—always.",
  "You are your only limit.",
  "Your destiny waits on the other side of fear.",
  "A burning heart never loses.",
  "Write your story with bravery.",
  "You are a storm of potential.",
  "The brave create their own luck.",
  "Your future is shaped by your today.",
  "Don’t wait—begin.",
  "Your dream must be chased fiercely.",
  "Let nothing stop your momentum.",
  "You were made for high seas and high dreams.",
  "Rise until rising becomes easy.",
  "Your heart is stronger than your doubts.",
  "Dream boldly—act bravely.",
  "The world needs your ambition.",
  "Push beyond your limits.",
  "Your story is your power.",
  "Even kings start from nothing.",
  "Believe you can—and you will.",
  "Your fire is eternal.",
  "Let your dream be your North Star.",
  "Great things take time—move anyway.",
  "You are capable of impossible things.",
  "Raise your flag—your era is coming.",
  "The more that you read, the more things you will know.",
];


export const getRandomQuote = (exclude: number[] = []): { quote: string; index: number } => {
  const available = motivationalQuotes
    .map((q, i) => ({ quote: q, index: i }))
    .filter(item => !exclude.includes(item.index));

  if (available.length === 0) {
    // Reset if all seen
    const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
    return { quote: motivationalQuotes[randomIndex], index: randomIndex };
  }

  const randomItem = available[Math.floor(Math.random() * available.length)];
  return randomItem;
};
